language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

branches:
  only:
  - master
  - develop

install:
  - sudo sudo apt-get install -y pylint
  - sudo pip install -U pytest
  - sudo python -m pip install --upgrade pip
  - sudo pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD

# command to run tests
script:
  - echo "pylint --errors-only *.py ... "
  - pylint --errors-only *.py

  #- echo "pytest ... "
  #- pytest
 
  - echo "simple test ... "
  - python unittesto_parser.py test/example/test_simple.xml > /tmp/test_simple.html

  - echo "multi tests ... "
  - python unittesto_parser.py test/example/test_multi.xml > /tmp/test_multi.html
